Regression testing recovered
git-svn-id: https://oops.math.spbu.ru/svn/checked/trunk@9 454aa00d-cbff-0310-9ee6-ad4123b06f8f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -884,7 +884,7 @@ esac
     else
       echo "$as_me: WARNING: no configuration information is in $ac_dir" >&2
     fi
-    cd $ac_popdir
+    cd "$ac_popdir"
   done
 fi
 
@@ -2537,6 +2537,93 @@ fi
 
 
 
+echo "$as_me:$LINENO: checking for Pr_o (pr_o.cmo)" >&5
+echo $ECHO_N "checking for Pr_o (pr_o.cmo)... $ECHO_C" >&6
+cat > conftest.ml <<EOF
+#load "pr_o.cmo";
+EOF
+if $CAMLP4R $PARSER_INCLUDES conftest.ml > /dev/null 2>&1 ; then
+    echo "$as_me:$LINENO: result: found" >&5
+echo "${ECHO_T}found" >&6
+else
+    unset found
+    if ! test "$use_findlib" = no ; then
+	if check_inc=`$OCAMLFIND query -i-format Pr_o 2>/dev/null`; then
+	    if $CAMLP4R $PARSER_INCLUDES $check_inc conftest.ml > /dev/null 2>&1 ; then
+		echo "$as_me:$LINENO: result: adding $check_inc" >&5
+echo "${ECHO_T}adding $check_inc" >&6
+		PARSER_INCLUDES="$PARSER_INCLUDES $check_inc"
+		found=yes
+	    fi
+	fi
+    fi
+    if ! test "$found"; then
+	for check_dir in +camlp4 $SITELIBDIR/Pr_o; do
+	    if $CAMLP4R -I $check_dir conftest.ml > /dev/null 2>&1 ; then
+		found=yes
+		break
+	    fi
+	done
+	if test "$found" ; then
+	    echo "$as_me:$LINENO: result: adding -I $check_dir" >&5
+echo "${ECHO_T}adding -I $check_dir" >&6
+	    PARSER_INCLUDES="$PARSER_INCLUDES -I $check_dir"
+	else
+	    echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+	    { { echo "$as_me:$LINENO: error: Required module Pr_o not found" >&5
+echo "$as_me: error: Required module Pr_o not found" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+    fi
+fi
+
+
+
+echo "$as_me:$LINENO: checking for q_MLast (q_MLast.cmo)" >&5
+echo $ECHO_N "checking for q_MLast (q_MLast.cmo)... $ECHO_C" >&6
+cat > conftest.ml <<EOF
+#load "q_MLast.cmo";
+EOF
+if $CAMLP4R $PARSER_INCLUDES conftest.ml > /dev/null 2>&1 ; then
+    echo "$as_me:$LINENO: result: found" >&5
+echo "${ECHO_T}found" >&6
+else
+    unset found
+    if ! test "$use_findlib" = no ; then
+	if check_inc=`$OCAMLFIND query -i-format q_MLast 2>/dev/null`; then
+	    if $CAMLP4R $PARSER_INCLUDES $check_inc conftest.ml > /dev/null 2>&1 ; then
+		echo "$as_me:$LINENO: result: adding $check_inc" >&5
+echo "${ECHO_T}adding $check_inc" >&6
+		PARSER_INCLUDES="$PARSER_INCLUDES $check_inc"
+		found=yes
+	    fi
+	fi
+    fi
+    if ! test "$found"; then
+	for check_dir in +camlp4 $SITELIBDIR/q_MLast; do
+	    if $CAMLP4R -I $check_dir conftest.ml > /dev/null 2>&1 ; then
+		found=yes
+		break
+	    fi
+	done
+	if test "$found" ; then
+	    echo "$as_me:$LINENO: result: adding -I $check_dir" >&5
+echo "${ECHO_T}adding -I $check_dir" >&6
+	    PARSER_INCLUDES="$PARSER_INCLUDES -I $check_dir"
+	else
+	    echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+	    { { echo "$as_me:$LINENO: error: Required module q_MLast not found" >&5
+echo "$as_me: error: Required module q_MLast not found" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+    fi
+fi
+
+
+
+
 
 for module in View; do
     echo "$as_me:$LINENO: checking for typeutil ($module)" >&5
@@ -3468,11 +3555,6 @@ esac
   *) ac_INSTALL=$ac_top_builddir$INSTALL ;;
   esac
 
-  if test x"$ac_file" != x-; then
-    { echo "$as_me:$LINENO: creating $ac_file" >&5
-echo "$as_me: creating $ac_file" >&6;}
-    rm -f "$ac_file"
-  fi
   # Let's still pretend it is `configure' which instantiates (i.e., don't
   # use $as_me), people would be surprised to read:
   #    /* config.h.  Generated by config.status.  */
@@ -3511,6 +3593,12 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
 	 fi;;
       esac
     done` || { (exit 1); exit 1; }
+
+  if test x"$ac_file" != x-; then
+    { echo "$as_me:$LINENO: creating $ac_file" >&5
+echo "$as_me: creating $ac_file" >&6;}
+    rm -f "$ac_file"
+  fi
 _ACEOF
 cat >>$CONFIG_STATUS <<_ACEOF
   sed "$ac_vpsub
